# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: StretchGoals.fm - Create Ambitious Goals as You Start and Grow Your Business
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  The Stretch Goals podcast is hosted by Robert Dickerson and Scott Davis and each week we’ll share insights and lessons learned based on our experiences as Entrepreneurs. We’ll challenge you to create ambitious goals as you start and grow your business.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://stretchgoals.fm" # the base hostname & protocol for your site, e.g. http://example.com
audiourl: "https://audio.stretchgoals.fm"

#Feed Info/iTunes
managerName: "Robert Dickerson &amp; Scott Davis"
managerEmail: "robert@mapoutlearning.com"
organizationName: "Stretch Goals"
podcastSubtitle: "Stetch Goals Podcast with Robert &amp; Scott"
squareLogo: assets/images/podcasts/sg-podcast-logo.jpg


# Social media
twitter_username: stretchgoalsfm
youtube_channel: https://www.youtube.com/channel/UC9bgL2WxNcwux_6gENaf5Fw

rob_twitter_username: RobDickersonJr
rob_twitter_url: https://twitter.com/robdickersonjr
scott_twitter_username: The_Scott_Davis
scott_twitter_url: https://twitter.com/the_scott_davis

# Subscription links
itunes_subscribe: https://itunes.apple.com/us/podcast/stretch-goals/id1178454667
googleplay_subscribe: https://goo.gl/app/playmusic?ibi=com.google.PlayMusic&isi=691797987&ius=googleplaymusic&link=https://play.google.com/music/m/Igcwkk25hd3uvtoqqfqykrawsvm?t%3DStretch_Goals
rss_subscribe: http://feeds.soundcloud.com/users/soundcloud:users:267751618/sounds.rss
soundcloud_subscribe: https://soundcloud.com/stretchgoals

permalink: /:title/
future: true

# Build settings
markdown: kramdown
gems:
#  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - Gulpfile.js
  - package.json
  - aws.json

#sass:
#  sass_dir: _sass
#  style: compressed